apiVersion: v1
kind: Service
metadata:
  name: iidl-api-service # Name for the service
  namespace: main-homepage
spec:
  selector:
    app: iidl-api # MUST match the label on your API pods in deploy.yaml
  ports:
    - protocol: TCP
      port: 80 # Port the service listens on *within* the cluster
      targetPort: 3000 # Port your Node.js container listens on
  # type: ClusterIP # Default - only reachable inside cluster
