# {PATH_TO_THE_PROJECT}/.cd-manifest/api-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: iidl-api-service # Name for the service
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    app: iidl-api # MUST match the label on your API pods in deploy.yaml
  ports:
    - protocol: TCP
      port: 80 # Port the service listens on *within* the cluster
      targetPort: 8000 # Port your Node.js container listens on
  # type: ClusterIP # Default - only reachable inside cluster
