# {PATH_TO_THE_PROJECT}/.cd-manifest/cronjob-supabase-pinger.yaml
# --- CronJob to ping Supabase Edge Function every 25 minutes ---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: supabase-function-pinger
  namespace: main-homepage
spec:
  # Cron schedule: Run every 25 minutes
  schedule: "*/25 * * * *"

  # Prevent concurrent runs if a job takes longer than 25 mins
  concurrencyPolicy: Forbid

  # Keep history of last 3 successful and 1 failed job runs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  # Template for the Job that the CronJob will create
  jobTemplate:
    spec:
      # Optional: How long the Job can run before being terminated
      activeDeadlineSeconds: 120 # 2 minutes deadline for the curl request

      # Template for the Pod that the Job will create
      template:
        spec:
          containers:
            - name: supabase-function-pinger-container
              # Use a minimal image containing the curl utility
              image: curlimages/curl:latest # Or specify a version e.g., curlimages/curl:8.4.0

              # Environment variable to hold the function URL for clarity
              env:
                - name: FUNCTION_URL
                  value: "https://vtigodxfcbkovkyelevg.supabase.co/functions/v1/db-pinger"

              # The command to run inside the container
              command: ["curl"]
              args:
                # -f: Fail on server errors (4xx, 5xx) -> K8s Job fails
                # -s: Silent mode
                # -S: Show error message even in silent mode if -f fails
                # -o /dev/null: Discard response body (we only care about success/failure)
                # $(FUNCTION_URL): Target URL from env var
                - "-fsS"
                - "-o"
                - "/dev/null"
                - "$(FUNCTION_URL)"

          # Restart policy for the pod created by the Job.
          restartPolicy: OnFailure
