# {PATH_TO_THE_PROJECT}/.cd-manifest/secrets.yaml
# --- Template for Kubernetes Secret object ---
# Placeholders will be substituted by the GitHub Actions workflow using envsubst

apiVersion: v1
kind: Secret
metadata:
  name: iidl-secrets
  namespace: ${K8S_NAMESPACE}
type: Opaque
stringData:
  # These keys MUST match 'secretKeyRef.key' in your Deployment
  # These placeholder variables (e.g., ${MONGO_USERNAME}) MUST match
  # the environment variables set in the GitHub Actions substitution step.
  MONGO_ROOT_USERNAME: "${MONGO_USERNAME}"
  MONGO_ROOT_PASSWORD: "${MONGO_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  # Add other secrets as needed following the same pattern
  # ANOTHER_SECRET: "${ANOTHER_SECRET_KEY_FROM_GITHUB}"
