name: Docker Image CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: unist.krs.ncr.gov-ntruss.com
          username: ${{ secrets.REG_ACCESS_KEY }}
          password: ${{ secrets.REG_SECRET_KEY }}

      - name: Docker Build and push
        env:
          REG: unist.krs.ncr.gov-ntruss.com
          NAME: unist-iidl
          VERSION: 1.0.0
        run: |
          docker build -t $NAME -f frontend/Dockerfile ./frontend
          docker tag $NAME:latest $REG/$NAME:$VERSION
          docker push $REG/$NAME:$VERSION
